### ISSUE TITLE
یه راهنمایی میخوام

### ISSUE THREAD

**Issue by AriaMoradi** [elias8702/Byte-Of-Python-Persian#1]
سلام. خیلی علاقه مندم که کتاب خودم رو مثل این بنویسم و منتشر کنم میتونید راه نماییم کنید که از چه برنامه ها و ابزار هایی استفاده کنم؟

**Comment by elias8702** [comment]
<div dir=rtl>
با عرض سلام 
من برای ویرایش این کارها از gedit در لینوکس استفاده می‌کنم 
برای نمایش در حالت گیت هاب  هم از این دو برنامه استفاده می‌کنم
<div dir=ltr>

moratab-master
rtlmd-gh-pages

<div dir=rtl>
اگر مشکلی بود در خدمتم  سربازم شاید دیر به دیر بتونم جوابگو باشم.

**Comment by elias8702** [comment]
<div dir=rtl>

همچین برای راست چین چپ چین از دستور های زیر استفاده کنید
<div dir=ltr>
<div dir=rtl>

چپ به راست
```
<div dir=ltr>

```

 #<div dir=ltr>#
<div dir=rtl>

راست به چپ

```
<div dir=ltr>
```

#<div dir=rtl>#
